name: "Linting"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "develop"
      - "main"
      - "master"

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          # ci: install exact versions from package-lock.json
          #     fast, secure, predictable compared to npm install
          npm ci
          npm run check
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          # ci: install exact versions from package-lock.json
          #     fast, secure, predictable compared to npm install
          npm ci
          npm run build

      - name: Check that all built are committed
        run: |
          # Check if any changes are to be committed
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are uncommitted changes, please run:"
            echo "  npm run format"
            echo "  npm run build"
            echo "and commit the resulting changes before pushing."
            echo "See also CONTRIBUTING.md"
            exit 1
          fi
